// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3MOWMlkfw1aj4hPL9VHzRKZG36lBbG8',
    appId: '1:171669602068:web:f535cdd9f99096d03a0c01',
    messagingSenderId: '171669602068',
    projectId: 'casi-61305',
    authDomain: 'casi-61305.firebaseapp.com',
    storageBucket: 'casi-61305.firebasestorage.app',
    measurementId: 'G-NL9V6FGGS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWarUQ6AbaP_0bQJS5DDkhKi3lQnJ-i98',
    appId: '1:171669602068:android:2611e37bb6c992ce3a0c01',
    messagingSenderId: '171669602068',
    projectId: 'casi-61305',
    storageBucket: 'casi-61305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtxfviq5xisPiKMLlnQ_cD2TmlHdIxPJU',
    appId: '1:171669602068:ios:c50694ee49ab3a803a0c01',
    messagingSenderId: '171669602068',
    projectId: 'casi-61305',
    storageBucket: 'casi-61305.firebasestorage.app',
    iosBundleId: 'com.example.casi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtxfviq5xisPiKMLlnQ_cD2TmlHdIxPJU',
    appId: '1:171669602068:ios:c50694ee49ab3a803a0c01',
    messagingSenderId: '171669602068',
    projectId: 'casi-61305',
    storageBucket: 'casi-61305.firebasestorage.app',
    iosBundleId: 'com.example.casi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa3MOWMlkfw1aj4hPL9VHzRKZG36lBbG8',
    appId: '1:171669602068:web:7c6fcb9cd958eb8f3a0c01',
    messagingSenderId: '171669602068',
    projectId: 'casi-61305',
    authDomain: 'casi-61305.firebaseapp.com',
    storageBucket: 'casi-61305.firebasestorage.app',
    measurementId: 'G-V5FRV51WG1',
  );
}
