import 'package:casi/core/usecase/usecase.dart';
import 'package:casi/core/user/data/data_sources/user_remote_data_source.dart';
import 'package:casi/core/user/data/repositories/user_repository_impl.dart';
import 'package:casi/core/user/domain/repositories/user_repository.dart';
import 'package:casi/core/user/domain/usecases/watch_user.dart';
import 'package:casi/features/enrollment/data/data_sources/enrollment_remote_data_source.dart';
import 'package:casi/features/enrollment/data/repositories/enrollment_repository_impl.dart';
import 'package:casi/features/enrollment/domain/repositories/enrollment_repository.dart';
import 'package:casi/features/enrollment/domain/usecases/accept_ethics.dart';
import 'package:casi/features/enrollment/domain/usecases/create_pending_clinic.dart';
import 'package:casi/features/enrollment/domain/usecases/get_active_ethics.dart';
import 'package:casi/features/enrollment/domain/usecases/get_enrollment.dart';
import 'package:casi/features/enrollment/domain/usecases/query_clinics_prefix.dart';
import 'package:casi/features/enrollment/domain/usecases/set_enrollment_clinic.dart';
import 'package:casi/features/enrollment/presentation/bloc/enrollment_bloc.dart';
import 'package:casi/firebase_options.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:get_it/get_it.dart';
import 'package:firebase_auth/firebase_auth.dart' as fa;
import 'package:google_sign_in/google_sign_in.dart';

import 'core/user/cubit/user_cubit.dart';
import 'features/auth/data/data_sources/auth_remote_data_source.dart';
import 'features/auth/data/repositories/auth_repository_impl.dart';
import 'features/auth/domain/repositories/auth_repository.dart';
import 'features/auth/domain/usecases/get_current_user.dart';
import 'features/auth/domain/usecases/google_sign_in.dart';
import 'features/auth/domain/usecases/sign_out.dart';
import 'features/auth/presentation/bloc/auth_bloc.dart';

part 'init_dependencies.main.dart';
